export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
export const GET_MOVIE_RECOMMENDATIONS = "GET_MOVIE_RECOMMENDATIONS";
export const GET_MOVIE_TRAILERS = "GET_MOVIE_TRAILERS";